// Embedded verifier circuit cache binary data
// Generated by: cargo run --release --bin build_cache src/circuit/cache.bin

/// The embedded cache binary data (only when embedded_cache feature is enabled)
#[cfg(feature = "embedded_cache")]
pub const CACHE_DATA: &[u8] = include_bytes!("cache.bin");

/// Empty cache when embedded_cache feature is disabled
#[cfg(not(feature = "embedded_cache"))]
pub const CACHE_DATA: &[u8] = &[];
