name: PR check

on:
  pull_request:
    types: [opened, reopened, synchronize]

permissions:
  pull-requests: write

jobs:
  pr_check:
    name: Validate PR
    runs-on: ubuntu-latest
    steps:
      - name: Set up keywords
        id: setup_keywords
        env:
          RESTRICTED_KEYWORDS_JSON: ${{ secrets.RESTRICTED_KEYWORDS }}
        run: echo "RESTRICTED_KEYWORDS=$(echo "$RESTRICTED_KEYWORDS_JSON" | jq -r '.[]' | tr '\n' ' ')" >> $GITHUB_ENV

      - name: Check for spam PR
        id: check
        env:
          PR_TITLE: ${{ github.event.pull_request.title }}
          PR_BODY: ${{ github.event.pull_request.body }}
        run: |
          # Initialize variables to track spam presence
          title_is_spam=false
          description_is_spam=false
          
          # Check title for spam
          for keyword in $RESTRICTED_KEYWORDS; do
            if echo "$PR_TITLE" | grep -i -q "$keyword"; then
              title_is_spam=true
              break
            fi
          done

          # Check description for spam
          for keyword in $RESTRICTED_KEYWORDS; do
            if echo "$PR_BODY" | grep -i -q "$keyword"; then
              description_is_spam=true
              break
            fi
          done

          # Set the output based on the presence of spam
          if [ "$title_is_spam" = true ] || [ "$description_is_spam" = true ]; then
            echo "is_spam=true" >> $GITHUB_ENV
          else
            echo "is_spam=false" >> $GITHUB_ENV
          fi

      - name: Checkout repository
        uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6
        with:
          persist-credentials: false

      - name: Close PR if spam are found and author is not a contributor or member
        if: ${{ env.is_spam == 'true' && github.event.pull_request.author_association == 'FIRST_TIME_CONTRIBUTOR' }}
        run: gh pr close "$PR_NUMBER" --comment "Spam detected"
        env:
          PR_NUMBER: ${{ github.event.pull_request.number }}
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}